### ISSUE TITLE
caverunner2 run

### ISSUE THREAD

**Issue by atom992** [kerrishotts/PhoneGap-HotShot-3-x-Code-Bundle#1]

**Comment by atom992** [comment]
as the book says:
add the
following line just before document.addEventListener( "deviceready", …):
Parse.initialize("YourApplicationID","YourJavascriptKey");
where should I add the code in the app.js?
https://github.com/kerrishotts/PhoneGap-HotShot-3-x-Code-Bundle/blob/master/caverunner/www/js/app.js
after line 81?

**Comment by kerrishotts** [comment]
Inserting it between lines 82 and 83 should be fine.

**Comment by atom992** [comment]
Thank you very much!

From: Kerri Shotts
Date: 2015-03-06 11:02
To: kerrishotts/PhoneGap-HotShot-3-x-Code-Bundle
CC: atom992
Subject: Re: [PhoneGap-HotShot-3-x-Code-Bundle] caverunner2 run (#1)
Inserting it between lines 82 and 83 should be fine.
